# Generated by Django 2.2.16 on 2022-03-08 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20211230_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.TextField(blank=True, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2022, message='Год не может быть больше текущего!')], verbose_name='Дата выхода'),
        ),
    ]
